export const STAFF_CONFIG = {
  demoMode: process.env.NEXT_PUBLIC_DEMO_MODE === "true",

  identityServerUrl:
    process.env.NEXT_PUBLIC_IDENTITY_SERVER_URL ?? "http://localhost:8081",

  services: {
    ird: process.env.IRD_SERVICE_URL ?? "http://localhost:8090",
    winz: process.env.WINZ_SERVICE_URL ?? "http://localhost:8091",
    moh: process.env.MOH_SERVICE_URL ?? "http://localhost:8092",
    dia: process.env.DIA_SERVICE_URL ?? "http://localhost:8093",
    nzta: process.env.NZTA_SERVICE_URL ?? "http://localhost:8094",
    acc: process.env.ACC_SERVICE_URL ?? "http://localhost:8095",
    nzqa: process.env.NZQA_SERVICE_URL ?? "http://localhost:8099",
    msd: process.env.MSD_SERVICE_URL ?? "http://localhost:8100",
    mbie: process.env.MBIE_SERVICE_URL ?? "http://localhost:8101",
    linz: process.env.LINZ_SERVICE_URL ?? "http://localhost:8102",
    statsnz: process.env.STATSNZ_SERVICE_URL ?? "http://localhost:8103",
    corrections: process.env.CORRECTIONS_SERVICE_URL ?? "http://localhost:8104",
    customs: process.env.CUSTOMS_SERVICE_URL ?? "http://localhost:8105",
    mpi: process.env.MPI_SERVICE_URL ?? "http://localhost:8106",
    doc: process.env.DOC_SERVICE_URL ?? "http://localhost:8107",
    tpk: process.env.TPK_SERVICE_URL ?? "http://localhost:8108",
    nzsis: process.env.NZSIS_SERVICE_URL ?? "http://localhost:8147",
    gcsb: process.env.GCSB_SERVICE_URL ?? "http://localhost:8146",
    nzdf: process.env.NZDF_SERVICE_URL ?? "http://localhost:8145",
    defence: process.env.DEFENCE_SERVICE_URL ?? "http://localhost:8144",
    mfat: process.env.MFAT_SERVICE_URL ?? "http://localhost:8143",
    mch: process.env.MCH_SERVICE_URL ?? "http://localhost:8142",
    tec: process.env.TEC_SERVICE_URL ?? "http://localhost:8141",
    ero: process.env.ERO_SERVICE_URL ?? "http://localhost:8140",
    moe: process.env.MOE_SERVICE_URL ?? "http://localhost:8139",
    fenz: process.env.FENZ_SERVICE_URL ?? "http://localhost:8138",
    maritime: process.env.MARITIME_SERVICE_URL ?? "http://localhost:8137",
    caa: process.env.CAA_SERVICE_URL ?? "http://localhost:8136",
    mot: process.env.MOT_SERVICE_URL ?? "http://localhost:8135",
    eqc: process.env.EQC_SERVICE_URL ?? "http://localhost:8134",
    mfe: process.env.MFE_SERVICE_URL ?? "http://localhost:8133",
    retirement: process.env.RETIREMENT_SERVICE_URL ?? "http://localhost:8132",
    worksafe: process.env.WORKSAFE_SERVICE_URL ?? "http://localhost:8131",
    regulation: process.env.REGULATION_SERVICE_URL ?? "http://localhost:8130",
    tearawhiti: process.env.TEARAWHITI_SERVICE_URL ?? "http://localhost:8129",
    ethnic: process.env.ETHNIC_SERVICE_URL ?? "http://localhost:8128",
    pacific: process.env.PACIFIC_SERVICE_URL ?? "http://localhost:8127",
    women: process.env.WOMEN_SERVICE_URL ?? "http://localhost:8126",
    oranga: process.env.ORANGA_SERVICE_URL ?? "http://localhost:8125",
    sfo: process.env.SFO_SERVICE_URL ?? "http://localhost:8124",
    crownlaw: process.env.CROWNLAW_SERVICE_URL ?? "http://localhost:8123",
    publicservice: process.env.PUBLICSERVICE_SERVICE_URL ?? "http://localhost:8122",
    dpmc: process.env.DPMC_SERVICE_URL ?? "http://localhost:8121",
    treasury: process.env.TREASURY_SERVICE_URL ?? "http://localhost:8120",
  },

  sessionCookieName: "tpt_staff_session",
  staffIdCookieName: "tpt_staff_id",

  sessionTtlSeconds: 60 * 60 * 8,

  get sessionSecret(): string {
    return process.env.TPT__GOV__SESSION_SECRET ?? "dev-insecure-session-secret-change-me";
  },
} as const;

export type StaffDeptId = "ird" | "winz" | "moh" | "dia" | "nzta" | "acc" | "nzqa" | "msd" | "mbie" | "linz" | "statsnz" | "corrections" | "customs" | "mpi" | "doc" | "tpk" | "nzsis" | "gcsb" | "nzdf" | "defence" | "mfat" | "mch" | "tec" | "ero" | "moe" | "fenz" | "maritime" | "caa" | "mot" | "eqc" | "mfe" | "retirement" | "worksafe" | "regulation" | "tearawhiti" | "ethnic" | "pacific" | "women" | "oranga" | "sfo" | "crownlaw" | "publicservice" | "dpmc" | "nzsis" | "gcsb" | "nzdf" | "defence" | "mfat" | "mch" | "tec" | "ero" | "moe" | "fenz" | "maritime" | "caa" | "mot" | "eqc" | "mfe" | "retirement" | "worksafe" | "regulation" | "tearawhiti" | "ethnic" | "pacific" | "women" | "oranga" | "sfo" | "crownlaw" | "publicservice" | "dpmc" | "treasury";

export interface StaffDeptMeta {
  id: StaffDeptId;
  name: string;
  shortName: string;
  description: string;
  scopes: string[  {
    id: "treasury",
    name: "The Treasury",
    shortName: "Treasury",
    description: "Crown financial management, the Budget and economic forecasts.",
    scopes: ["treasury:budget", "treasury:economic-outlook"],
    href: "/dept/treasury",
  },
  {
    id: "dpmc",
    name: "Department of the Prime Minister and Cabinet",
    shortName: "DPMC",
    description: "Cabinet support, honours and national security coordination.",
    scopes: ["dpmc:honours", "dpmc:engagements"],
    href: "/dept/dpmc",
  },
  {
    id: "publicservice",
    name: "Te Kawa Mataaho Public Service Commission",
    shortName: "Public Service",
    description: "Workforce data and capability ratings across public agencies.",
    scopes: ["publicservice:workforce", "publicservice:agency-ratings"],
    href: "/dept/publicservice",
  },
  {
    id: "crownlaw",
    name: "Crown Law Office",
    shortName: "Crown Law",
    description: "Government legal opinions and litigation the Crown is involved in.",
    scopes: ["crownlaw:legal-opinions", "crownlaw:litigation"],
    href: "/dept/crownlaw",
  },
  {
    id: "sfo",
    name: "Serious Fraud Office",
    shortName: "SFO",
    description: "Investigations into serious or complex fraud.",
    scopes: ["sfo:investigations", "sfo:outcomes"],
    href: "/dept/sfo",
  },
  {
    id: "oranga",
    name: "Oranga Tamariki",
    shortName: "Oranga Tamariki",
    description: "Care, protection and support services for children and young people.",
    scopes: ["oranga:care-placements", "oranga:support-services"],
    href: "/dept/oranga",
  },
  {
    id: "women",
    name: "Ministry for Women",
    shortName: "Women",
    description: "Programmes and insights to improve outcomes for women and girls.",
    scopes: ["women:programmes", "women:insights"],
    href: "/dept/women",
  },
  {
    id: "pacific",
    name: "Ministry for Pacific Peoples",
    shortName: "Pacific Peoples",
    description: "Programmes, language services and support for Pacific communities.",
    scopes: ["pacific:programmes", "pacific:language-services"],
    href: "/dept/pacific",
  },
  {
    id: "ethnic",
    name: "Ministry for Ethnic Communities",
    shortName: "Ethnic Communities",
    description: "Support, grants and engagement for ethnic communities.",
    scopes: ["ethnic:programmes", "ethnic:community-grants"],
    href: "/dept/ethnic",
  },
  {
    id: "tearawhiti",
    name: "Te Arawhiti",
    shortName: "Te Arawhiti",
    description: "Office for Māori Crown Relations — Treaty settlement and engagement.",
    scopes: ["tearawhiti:treaty-settlements", "tearawhiti:engagements"],
    href: "/dept/tearawhiti",
  },
  {
    id: "regulation",
    name: "Ministry for Regulation",
    shortName: "Regulation",
    description: "Regulatory reviews, system stewardship and better regulation.",
    scopes: ["regulation:regulatory-reviews", "regulation:proposals"],
    href: "/dept/regulation",
  },
  {
    id: "worksafe",
    name: "WorkSafe New Zealand",
    shortName: "WorkSafe",
    description: "Workplace health, safety and injury insurance.",
    scopes: ["worksafe:inspections", "worksafe:investigations"],
    href: "/dept/worksafe",
  },
  {
    id: "retirement",
    name: "Retirement Commission (Te Ara Ahunga Ora)",
    shortName: "Retirement",
    description: "Retirement income policy, planning and guidance.",
    scopes: ["retirement:retirement-plan", "retirement:guidance"],
    href: "/dept/retirement",
  },
  {
    id: "mfe",
    name: "Ministry for the Environment",
    shortName: "MfE",
    description: "Environmental reporting, emissions and resource management.",
    scopes: ["mfe:emissions", "mfe:reports"],
    href: "/dept/mfe",
  },
  {
    id: "eqc",
    name: "Earthquake Commission (Toka Tū Ake)",
    shortName: "EQC",
    description: "Natural disaster insurance for homes and land.",
    scopes: ["eqc:claims", "eqc:cover"],
    href: "/dept/eqc",
  },
  {
    id: "mot",
    name: "Ministry of Transport",
    shortName: "Transport",
    description: "Transport policy, strategies and investment.",
    scopes: ["mot:strategies", "mot:programmes"],
    href: "/dept/mot",
  },
  {
    id: "caa",
    name: "Civil Aviation Authority",
    shortName: "CAA",
    description: "Aviation safety, pilot licences and aircraft registry.",
    scopes: ["caa:licences", "caa:aircraft"],
    href: "/dept/caa",
  },
  {
    id: "maritime",
    name: "Maritime New Zealand",
    shortName: "Maritime",
    description: "Maritime safety, response and vessel regulation.",
    scopes: ["maritime:vessels", "maritime:incidents"],
    href: "/dept/maritime",
  },
  {
    id: "fenz",
    name: "Fire and Emergency New Zealand",
    shortName: "FENZ",
    description: "Fire safety, emergency response and risk information.",
    scopes: ["fenz:fire-safety", "fenz:incidents"],
    href: "/dept/fenz",
  },
  {
    id: "moe",
    name: "Ministry of Education",
    shortName: "Education",
    description: "Education policy, enrolment and student support.",
    scopes: ["moe:enrolment", "moe:student-support"],
    href: "/dept/moe",
  },
  {
    id: "ero",
    name: "Education Review Office",
    shortName: "ERO",
    description: "Reviews and reports on early learning and schools.",
    scopes: ["ero:reviews", "ero:reports"],
    href: "/dept/ero",
  },
  {
    id: "tec",
    name: "Tertiary Education Commission",
    shortName: "TEC",
    description: "Tertiary funding, courses and provider performance.",
    scopes: ["tec:funding", "tec:courses"],
    href: "/dept/tec",
  },
  {
    id: "mch",
    name: "Ministry for Culture and Heritage",
    shortName: "MCH",
    description: "Arts, culture, heritage and broadcasting.",
    scopes: ["mch:heritage-sites", "mch:grants"],
    href: "/dept/mch",
  },
  {
    id: "mfat",
    name: "Ministry of Foreign Affairs and Trade",
    shortName: "MFAT",
    description: "Foreign affairs, trade and overseas missions.",
    scopes: ["mfat:overseas-missions", "mfat:travel-advisories"],
    href: "/dept/mfat",
  },
  {
    id: "defence",
    name: "Ministry of Defence",
    shortName: "Defence",
    description: "Defence policy, procurement and basing.",
    scopes: ["defence:procurements", "defence:bases"],
    href: "/dept/defence",
  },
  {
    id: "nzdf",
    name: "New Zealand Defence Force",
    shortName: "NZDF",
    description: "Defence personnel, services and operations.",
    scopes: ["nzdf:service-records", "nzdf:deployments"],
    href: "/dept/nzdf",
  },
  {
    id: "gcsb",
    name: "Government Communications Security Bureau",
    shortName: "GCSB",
    description: "Cyber security, signals intelligence and mandates.",
    scopes: ["gcsb:mandates", "gcsb:engagements"],
    href: "/dept/gcsb",
  },
  {
    id: "nzsis",
    name: "New Zealand Security Intelligence Service",
    shortName: "NZSIS",
    description: "National security intelligence and counter-intelligence.",
    scopes: ["nzsis:mandates", "nzsis:threats"],
    href: "/dept/nzsis",
  },
];
  href: string;
}

export const STAFF_DEPARTMENTS: StaffDeptMeta[] = [
  {
    id: "ird",
    name: "Inland Revenue",
    shortName: "IRD",
    description: "Income tax, GST, KiwiSaver and Working for Families.",
    scopes: ["ird:income", "ird:tax-summary", "ird:gst", "ird:kiwisaver", "ird:wff"],
    href: "/dept/ird",
  },
  {
    id: "winz",
    name: "Work and Income",
    shortName: "WINZ",
    description: "Benefits, payments and appointments.",
    scopes: ["winz:benefit-status", "winz:payments"],
    href: "/dept/winz",
  },
  {
    id: "moh",
    name: "Ministry of Health",
    shortName: "MOH",
    description: "GP enrolment, prescriptions, appointments and vaccinations.",
    scopes: ["moh:nhi", "moh:prescriptions", "moh:appointments"],
    href: "/dept/moh",
  },
  {
    id: "dia",
    name: "Department of Internal Affairs",
    shortName: "DIA",
    description: "Passports, citizenship and official documents.",
    scopes: ["dia:passport", "dia:birth-certificate"],
    href: "/dept/dia",
  },
  {
    id: "nzta",
    name: "Waka Kotahi NZ Transport Agency",
    shortName: "NZTA",
    description: "Driver licence, vehicles and road user charges.",
    scopes: ["nzta:licence", "nzta:vehicles"],
    href: "/dept/nzta",
  },
  {
    id: "acc",
    name: "Accident Compensation Corporation",
    shortName: "ACC",
    description: "Injury claims, entitlements and rehabilitation.",
    scopes: ["acc:claims", "acc:entitlements", "acc:rehabilitation"],
    href: "/dept/acc",
  },
  {
    id: "nzqa",
    name: "Ministry of Education / NZQA",
    shortName: "NZQA",
    description: "Qualifications, transcripts and the New Zealand Record of Achievement.",
    scopes: ["nzqa:qualifications", "nzqa:transcripts"],
    href: "/dept/nzqa",
  },
  {
    id: "msd",
    name: "Ministry of Social Development",
    shortName: "MSD",
    description: "StudyLink student loans and allowances, and cross-service case history.",
    scopes: ["msd:studylink", "msd:case-history"],
    href: "/dept/msd",
  },
  {
    id: "mbie",
    name: "Ministry of Business, Innovation and Employment",
    shortName: "MBIE",
    description: "Business registrations and company director lookup.",
    scopes: ["mbie:business", "mbie:directorships"],
    href: "/dept/mbie",
  },
  {
    id: "linz",
    name: "Toitū Te Whenua Land Information New Zealand",
    shortName: "LINZ",
    description: "Property titles and land ownership records.",
    scopes: ["linz:titles", "linz:ownership"],
    href: "/dept/linz",
  },
  {
    id: "statsnz",
    name: "Statistics New Zealand",
    shortName: "Stats NZ",
    description: "Census data, official statistics and your data profile.",
    scopes: ["statsnz:census", "statsnz:profile"],
    href: "/dept/statsnz",
  },
  {
    id: "corrections",
    name: "Department of Corrections",
    shortName: "Corrections",
    description: "Probation status and case information.",
    scopes: ["corrections:probation", "corrections:case"],
    href: "/dept/corrections",
  },
  {
    id: "customs",
    name: "New Zealand Customs Service",
    shortName: "Customs",
    description: "Traveller declarations and arrival information.",
    scopes: ["customs:travel", "customs:declarations"],
    href: "/dept/customs",
  },
  {
    id: "mpi",
    name: "Ministry for Primary Industries",
    shortName: "MPI",
    description: "Food and business registrations and certifications.",
    scopes: ["mpi:registrations", "mpi:certifications"],
    href: "/dept/mpi",
  },
  {
    id: "doc",
    name: "Department of Conservation",
    shortName: "DOC",
    description: "Conservation permits and concessions.",
    scopes: ["doc:permits", "doc:concessions"],
    href: "/dept/doc",
  },
  {
    id: "tpk",
    name: "Te Puni Kōkiri",
    shortName: "TPK",
    description: "Māori development programmes and funding.",
    scopes: ["tpk:programmes", "tpk:funding"],
    href: "/dept/tpk",
  },
];

/** The fictional demo citizen shared with the citizen portal. */
export const DEMO_CITIZEN_DID = "did:gov:nz:demo-alex-tane";
export const DEMO_CITIZEN_NAME = "Alex Tane";
